### ISSUE TITLE
Option to remove sections and controls

### ISSUE THREAD

**Issue by dlzi** [RiseLedger/rise-options#1]
Hello.

It would be nice to be able to remove controls and sections. Is there a way to do that?

**Comment by RiseLedger** [comment]
Hi. I have just updated the RiseOptions.php file. So now you can delete the sections.
To delete for example the Site Title & Tagline you will use this code:
RiseOptions::removeSection('title_tagline');

For controls it is not yet implemented. If you have any ideas of improving the rise-options let me know and I will notice for the future updates. Thanks

**Comment by dlzi** [comment]
Hi. Thank you very much for that. Your class is getting handy. I believe once you add a patch for #2 and allow us  to remove controls, you will had covered the basic needs to create a standard theme customizer. Well done!
